import sys
import re

try:
    sys.stdout.reconfigure(encoding='utf-8')
except AttributeError:
    pass

def replace_block(lines, start_sub, end_sub, replacement_lines, start_from=0, search_backwards=False):
    start_idx = -1
    for idx in range(start_from, len(lines)):
        if start_sub in lines[idx]:
            start_idx = idx
            break
    if start_idx == -1:
        print(f"Warning: could not find start: '{start_sub}'")
        return -1
    
    end_idx = -1
    if search_backwards:
        for idx in range(len(lines) - 1, start_idx - 1, -1):
            if end_sub in lines[idx]:
                end_idx = idx + 1
                break
    else:
        for idx in range(start_idx, len(lines)):
            if end_sub in lines[idx]:
                end_idx = idx + 1
                break
    if end_idx == -1:
        print(f"Warning: could not find end: '{end_sub}'")
        return -1
    
    lines[start_idx:end_idx] = replacement_lines
    return start_idx + len(replacement_lines)

def clean_trade_viewer():
    p = r'D:\부동산업무\antigravity\consult_diary\scratch\중개수첩_오토봇.exe_extracted\PYZ.pyz_extracted\decompiled\trade_viewer.py'
    raw_lines = open(p, 'r', encoding='utf-8', errors='ignore').read().splitlines()

    # 1. Split header and body (unindenting by 12 spaces)
    header_lines = raw_lines[:49]
    body_lines = []
    for line in raw_lines[54:]:
        if line.startswith('            '):
            body_lines.append(line[12:])
        elif line.strip() == '':
            body_lines.append('')
        else:
            body_lines.append(line.lstrip())
    
    lines = header_lines + body_lines

    # Find the start of def run_trade_viewer and truncate everything after
    run_tv_idx = -1
    for idx, line in enumerate(lines):
        if line.startswith('def run_trade_viewer'):
            run_tv_idx = idx
            break
    if run_tv_idx != -1:
        lines = lines[:run_tv_idx]

    # 2. format_member_name
    replace_block(lines, 'def format_member_name(name):', 'return f"{name} 공인중개사"', [
        'def format_member_name(name):',
        '    if not name:',
        '        return "공인중개사"',
        '    if any(suffix in name for suffix in ("공인중개사", "사무소", "부동산", "컨설팅", "대표")):',
        '        return name',
        '    return f"{name} 공인중개사"'
    ])

    # 3. get_expos_unit_details and get_kakao_address_info
    expos_unit_and_kakao_code = [
        'def get_expos_unit_details(sigungu, bjdong, bun, ji, ho_name, dong_name):',
        '    try:',
        '        if not ho_name:',
        '            return None',
        '        url_info = "https://apis.data.go.kr/1613000/BldRgstHubService/getBrExposInfo"',
        '        url_area = "https://apis.data.go.kr/1613000/BldRgstHubService/getBrExposPubuseAreaInfo"',
        '        bun_str = str(bun).zfill(4) if bun else "0000"',
        '        ji_str = str(ji).zfill(4) if ji else "0000"',
        '        result = {"area": None, "supply_area": None, "flrNo": None, "violBldYn": "N", "hoNm": ""}',
        '        for plat in (0, 1, 2):',
        '            query = f"?serviceKey={GOV_API_KEY}&sigunguCd={sigungu}&bjdongCd={bjdong}&platGbCd={plat}&bun={bun_str}&ji={ji_str}&numOfRows=1000&pageNo=1&_type=json"',
        '            req_info = urllib.request.Request(url_info + query)',
        '            req_info.add_header("User-Agent", "Mozilla/5.0")',
        '            req_info.add_header("Accept", "application/json, text/plain, */*")',
        '            try:',
        '                with urllib.request.urlopen(req_info, timeout=5) as resp:',
        '                    res_body = resp.read().decode("utf-8")',
        '                if res_body.strip():',
        '                    data = json.loads(res_body)',
        '                    items = data.get("response", {}).get("body", {}).get("items", {}).get("item", [])',
        '                    if items:',
        '                        if isinstance(items, dict):',
        '                            items = [items]',
        '                        for item in items:',
        '                            item_ho = str(item.get("hoNm") or "")',
        '                            item_dong = str(item.get("dongNm") or "")',
        '                            if ho_name not in item_ho and item_ho not in ho_name:',
        '                                continue',
        '                            if dong_name and not match_dong(dong_name, item_dong):',
        '                                continue',
        '                            result["flrNo"] = item.get("flrNo")',
        '                            result["violBldYn"] = item.get("violBldYn", "N")',
        '                            result["hoNm"] = item_ho',
        '            except Exception as e:',
        '                print(f"표제부/전유부 API 조회 중 오류: {e}")',
        '',
        '            req_area = urllib.request.Request(url_area + query)',
        '            req_area.add_header("User-Agent", "Mozilla/5.0")',
        '            req_area.add_header("Accept", "application/json, text/plain, */*")',
        '            try:',
        '                with urllib.request.urlopen(req_area, timeout=5) as resp:',
        '                    res_body = resp.read().decode("utf-8")',
        '                if res_body.strip():',
        '                    data = json.loads(res_body)',
        '                    items = data.get("response", {}).get("body", {}).get("items", {}).get("item", [])',
        '                    if items:',
        '                        if isinstance(items, dict):',
        '                            items = [items]',
        '                        area_exclusive = 0.0',
        '                        area_supply = 0.0',
        '                        for item in items:',
        '                            item_ho = str(item.get("hoNm") or "")',
        '                            item_dong = str(item.get("dongNm") or "")',
        '                            if ho_name not in item_ho and item_ho not in ho_name:',
        '                                continue',
        '                            if dong_name and not match_dong(dong_name, item_dong):',
        '                                continue',
        '                            val = item.get("area")',
        '                            if not val:',
        '                                continue',
        '                            f_val = float(val)',
        '                            area_supply += f_val',
        '                            if str(item.get("exposPubuseGbCd", "")) == "1":',
        '                                area_exclusive += f_val',
        '                        if area_supply > 0:',
        '                            result["area"] = round(area_exclusive, 2) if area_exclusive > 0 else round(area_supply, 2)',
        '                            result["supply_area"] = round(area_supply, 2)',
        '            except Exception as e:',
        '                print(f"공용면적 API 조회 중 오류: {e}")',
        '',
        '            if result["flrNo"] or result["area"]:',
        '                return result',
        '        return result',
        '    except Exception as e:',
        '        print(f"get_expos_unit_details 에러: {e}")',
        '        return None',
        '',
        'def get_kakao_address_info(address_str):',
        '    url = "https://dapi.kakao.com/v2/local/search/address.json"',
        '    headers = {"Authorization": f"KakaoAK {KAKAO_API_KEY}"}',
        '    params = urllib.parse.urlencode({"query": address_str})',
        '    req = urllib.request.Request(f"{url}?{params}", headers=headers)',
        '    try:',
        '        with urllib.request.urlopen(req, timeout=5) as response:',
        '            res_text = response.read().decode("utf-8")',
        '            data = json.loads(res_text)',
        '        if data.get("documents"):',
        '            doc = data["documents"][0]',
        '            addr = doc.get("address", {})',
        '            if not addr:',
        '                return None',
        '            b_code = addr.get("b_code", "")',
        '            h_code = addr.get("h_code", "")',
        '            code_to_use = b_code if len(b_code) >= 10 else h_code',
        '            if len(code_to_use) >= 10:',
        '                road_addr_val = ""',
        '                if doc.get("road_address"):',
        '                    road_addr_val = doc.get("road_address", {}).get("address_name", "")',
        '                return {',
        '                    "sigunguCd": code_to_use[:5],',
        '                    "bjdongCd": code_to_use[5:10],',
        '                    "bjdongNm": addr.get("region_3depth_name", ""),',
        '                    "bun": addr.get("main_address_no", ""),',
        '                    "ji": addr.get("sub_address_no", "0") or "0",',
        '                    "road_address": road_addr_val,',
        '                    "sidoNm": addr.get("region_1depth_name", ""),',
        '                    "sigunguNm": addr.get("region_2depth_name", "")',
        '                }',
        '        return None',
        '    except Exception as e:',
        '        print(f"카카오 API 에러: {e}")',
        '        return None'
    ]
    replace_block(lines, 'def get_expos_unit_details(sigungu, bjdong, bun, ji, ho_name, dong_name):', 'def normalize_jibun(jibun_str):', expos_unit_and_kakao_code)

    # 4. parse_address_and_ho
    replace_block(lines, 'def parse_address_and_ho(address_str):', 'ho_name)', [
        'def parse_address_and_ho(address_str):',
        '    address_str = address_str.strip()',
        '    words = address_str.split()',
        '    jibun_idx = -1',
        '    for idx, w in enumerate(words):',
        '        clean_w = w.strip(",.")',
        '        if re.match(r"^산?\\d+(-\\d+)?$", clean_w):',
        '            jibun_idx = idx',
        '    if jibun_idx == -1:',
        '        return (address_str, "", "")',
        '    clean_address = " ".join(words[:jibun_idx + 1])',
        '    extra_words = words[jibun_idx + 1:]',
        '    dong_name = ""',
        '    ho_name = ""',
        '    ',
        '    if len(extra_words) == 1:',
        '        word = extra_words[0].strip()',
        '        if "동" in word and "호" in word:',
        '            m = re.search(r"([A-Za-z0-9가-힣\\\\-]+)\\s*동\\s*([A-Za-z0-9가-힣\\\\-]+)\\s*호", word)',
        '            if m:',
        '                dong_name = m.group(1)',
        '                ho_name = m.group(2)',
        '        elif word.endswith("동"):',
        '            dong_name = word.replace("동", "")',
        '        elif word.endswith("호"):',
        '            ho_name = word.replace("호", "")',
        '        elif "-" in word:',
        '            parts = word.split("-")',
        '            if len(parts) == 2 and parts[0].isalnum() and parts[1].isalnum():',
        '                dong_name = parts[0]',
        '                ho_name = parts[1]',
        '        elif word.isalnum() and any(c.isdigit() for c in word):',
        '            ho_name = word',
        '    elif len(extra_words) >= 2:',
        '        w1 = extra_words[0].strip()',
        '        w2 = extra_words[1].strip()',
        '        d_match = re.search(r"([A-Za-z0-9가-힣\\\\-]+)\\s*동", w1)',
        '        h_match = re.search(r"([A-Za-z0-9가-힣\\\\-]+)\\s*호", w2)',
        '        dong_name = d_match.group(1) if d_match else w1.replace("동", "")',
        '        ho_name = h_match.group(1) if h_match else w2.replace("호", "")',
        '    return (clean_address, dong_name, ho_name)'
    ])

    # 5. fetch_trade_data_month
    fetch_trade_data_month_code = [
        'def fetch_trade_data_month(api_url, sigungu, deal_ymd):',
        '    if api_url.startswith("http://"):',
        '        api_url = api_url.replace("http://", "https://")',
        '    query = f"?serviceKey={GOV_API_KEY}&LAWD_CD={sigungu}&DEAL_YMD={deal_ymd}&numOfRows=1000&pageNo=1&_type=json"',
        '    req = urllib.request.Request(api_url + query)',
        '    req.add_header("User-Agent", "Mozilla/5.0")',
        '    try:',
        '        with urllib.request.urlopen(req, timeout=5) as response:',
        '            res_text = response.read().decode("utf-8")',
        '        if not res_text.strip():',
        '            return []',
        '        json_data = json.loads(res_text)',
        '        header = json_data.get("response", {}).get("header", {})',
        '        result_code = header.get("resultCode")',
        '        if result_code in ("30", "03") or "SERVICE_KEY_IS_NOT_REGISTERED_ERROR" in header.get("resultMsg", ""):',
        '            raise PermissionError("API 인증 오류")',
        '        elif result_code not in ("00", "000"):',
        '            return []',
        '        items = json_data.get("response", {}).get("body", {}).get("items", {}).get("item", [])',
        '        if not items:',
        '            return []',
        '        if isinstance(items, dict):',
        '            return [items]',
        '        return items',
        '    except urllib.error.HTTPError as e:',
        '        if e.code == 403:',
        '            raise PermissionError("403 Forbidden")',
        '        return []',
        '    except Exception as e:',
        '        print(f"fetch_trade_data_month 에러 ({deal_ymd}): {e}")',
        '        return []',
        'class TransactionList(list):'
    ]
    replace_block(lines, 'def fetch_trade_data_month(api_url, sigungu, deal_ymd):', 'class TransactionList(list):', fetch_trade_data_month_code)

    # 6. TransactionList class
    replace_block(lines, 'class TransactionList(list):', '__classdictcell__ = __module__', [
        'class TransactionList(list):',
        '    def __init__(self, *args, **kwargs):',
        '        super().__init__(*args, **kwargs)',
        '        self.trade_permission_error = False',
        '        self.rent_permission_error = False'
    ])

    # 7. nested quotes print line
    replace_block(lines, 'print(" -> [", f"{type_name}] 인근 유사 매물 검색 중', '±{int(area_margin * 100)}%내외)")', [
        '            print(f" -> [{type_name}] 인근 유사 매물 검색 중 (법정동: {bjdong_nm or \'전체\'}, 준공년도: {target_build_year or \'전체\'}±{build_year_margin}년, 면적: {f\'{target_area:.2f}㎡\' if target_area else \'전체\'}±{int(area_margin * 100)}%내외)")'
    ])

    # 8. check_moatown_and_redev
    moatown_redev_code = [
        'def check_moatown_and_redev(address):',
        '    clean_address, _, _ = parse_address_and_ho(address)',
        '    addr_info = get_kakao_address_info(clean_address)',
        '    if not addr_info:',
        '        return {"moatown": False, "moatown_name": "", "redev": False, "redev_name": ""}',
        '    bun_val = str(addr_info["bun"]).zfill(4) if addr_info["bun"] else "0000"',
        '    ji_val = str(addr_info["ji"]).zfill(4) if addr_info["ji"] else "0000"',
        '    pnu = f"{addr_info[\'sigunguCd\']}{addr_info[\'bjdongCd\']}1{bun_val}{ji_val}"',
        '    vworld_key = "80194C85-0EE3-3220-A3C1-3268AD8756B9"',
        '    url = f"https://api.vworld.kr/ned/data/getLandUseAttr?key={vworld_key}&domain=http://localhost&pnu={pnu}&format=json&numOfRows=100&pageNo=1"',
        '    req = urllib.request.Request(url)',
        '    req.add_header("Referer", "http://localhost")',
        '    result = {"moatown": False, "moatown_name": "", "redev": False, "redev_name": ""}',
        '    try:',
        '        with urllib.request.urlopen(req, timeout=5) as resp:',
        '            data = json.loads(resp.read().decode("utf-8"))',
        '            items = data.get("landUses", {}).get("field", [])',
        '            if not items:',
        '                items = data.get("response", {}).get("landUses", {}).get("field", [])',
        '        if items:',
        '            if isinstance(items, dict):',
        '                items = [items]',
        '            moatown_list = []',
        '            redev_list = []',
        '            for item in items:',
        '                name = item.get("prposAreaDstrcCodeNm", "")',
        '                if not name:',
        '                    continue',
        '                if any(kw in name for kw in ("소규모주택정비 관리지역", "소규모주택정비관리지역")) or ("소규모주택" in name and "관리지역" in name):',
        '                    moatown_list.append(name)',
        '                if any(kw in name for kw in ("정비구역", "재개발", "재건축", "도시환경정비")):',
        '                    redev_list.append(name)',
        '            if moatown_list:',
        '                result["moatown"] = True',
        '                result["moatown_name"] = ", ".join(list(set(moatown_list)))',
        '            if redev_list:',
        '                result["redev"] = True',
        '                result["redev_name"] = ", ".join(list(set(redev_list)))',
        '        return result',
        '    except Exception as e:',
        '        print(f"check_moatown_and_redev 에러: {e}")',
        '        return result'
    ]
    replace_block(lines, 'def check_moatown_and_redev(address):', 'return result', moatown_redev_code)

    # 9. safe_addr joined string logic
    replace_block(lines, '[c for c in address if not c in (" ", "-", "_")]', 'safe_addr = ##ERROR##("".join).strip()', [
        '        safe_addr = "".join([c for c in address if c not in (" ", "-", "_")]).strip()'
    ])

    # 10. get_sort_key function
    replace_block(lines, 'def get_sort_key(item):', 'trades.sort(key=get_sort_key)', [
        '                    def get_sort_key(item):',
        '                        area_val = item.get("excluUseAr") or item.get("totalFloorAr") or 0.0',
        '                        try:',
        '                            area = float(area_val)',
        '                        except:',
        '                            area = 0.0',
        '                        try:',
        '                            y = int(item.get("dealYear", 0))',
        '                            m = int(item.get("dealMonth", 0))',
        '                            d = int(item.get("dealDay", 0))',
        '                        except:',
        '                            y, m, d = 0, 0, 0',
        '                        return (area, -y, -m, -d)',
        '                    trades.sort(key=get_sort_key)'
    ])

    # 10b. Fix unclosed try block around expand_choice input
    exp_idx = -1
    for idx, line in enumerate(lines):
        if 'expand_choice = input("[입력] 분석 범위를 선택하세요' in line:
            exp_idx = idx
            break
    if exp_idx != -1 and 'try:' in lines[exp_idx - 1]:
        lines[exp_idx - 1] = '                if True:'

    # 11. dead code after return (trades, jeonses, ...)
    replace_block(lines, 'return (trades, jeonses, wolses, prop_type_name, selected_label, is_expanded)', 'floor_display = dong_info or f"{dong_prefix}{floor_str}" if floor_str else "-"', [
        '                    return (trades, jeonses, wolses, prop_type_name, selected_label, is_expanded)',
        '    except Exception as e:',
        '        print(f" [!] 오류 발생: {e}")'
    ], start_from=2000, search_backwards=True)

    # Clean up exit calls and compile issues
    clean_lines = []
    skip_dead = False
    for line in lines:
        if line.strip().startswith('def run_trade_viewer'):
            break
        if '__exit__(None, None, None)' in line or '##ERROR##(None, None, None)' in line:
            continue
        if 'return matches' in line:
            clean_lines.append(line)
            skip_dead = True
            continue
        if skip_dead:
            if 'def format_price' in line:
                skip_dead = False
            else:
                continue
        clean_lines.append(line)

    # 12. Reconstruct run_trade_viewer and add __main__ entry point
    run_trade_viewer_code = [
        'def run_trade_viewer(pre_address_info, pre_prop_type, target_floor, target_area):',
        '    target_build_year = None',
        '    target_house_type = None',
        '    if pre_address_info:',
        '        addr_info = pre_address_info',
        '        prop_type = pre_prop_type',
        '        clean_address = addr_info.get("address_name", "")',
        '        dong_name = ""',
        '        ho_name = ""',
        '    else:',
        '        print("\\n==================================================")',
        '        print("       실거래가 조회 및 비교 (로그인 불필요)       ")',
        '        print("==================================================")',
        '        print("  조회할 주소를 입력하시면 해당 지번의")',
        '        print("  최근 12개월 실거래가 내역과 차이를 비교해 줍니다.")',
        '        print("  (메뉴로 돌아가려면 \'q\' 또는 엔터를 입력하세요)")',
        '        print("--------------------------------------------------")',
        '        address = input("\\n[입력] 조회할 주소: ").strip()',
        '        if not address or address.lower() == "q":',
        '            return',
        '        clean_address, dong_name, ho_name = parse_address_and_ho(address)',
        '        print(" -> 주소 변환 중...")',
        '        addr_info = get_kakao_address_info(clean_address)',
        '        if not addr_info:',
        '            print(" [!] 주소 변환 실패! 주소를 정확히 입력하셨는지 확인해 주세요.")',
        '            return',
        '        display_road = addr_info.get("road_address") or "도로명 없음"',
        '        print(f" -> 주소 확인: {clean_address} ({display_road})")',
        '        print(" -> 부동산 유형 분석 중 (건축물대장 조회)...")',
        '        prop_type = None',
        '        bld_name = ""',
        '        etc_purp = ""',
        '        main_purp = ""',
        '        try:',
        '            bun_str = str(addr_info["bun"]).zfill(4) if addr_info.get("bun") else "0000"',
        '            ji_str = str(addr_info["ji"]).zfill(4) if addr_info.get("ji") else "0000"',
        '            title_url = "https://apis.data.go.kr/1613000/BldRgstHubService/getBrTitleInfo"',
        '            title_query = f"?serviceKey={GOV_API_KEY}&sigunguCd={addr_info[\'sigunguCd\']}&bjdongCd={addr_info[\'bjdongCd\']}&platGbCd=0&bun={bun_str}&ji={ji_str}&numOfRows=100&pageNo=1&_type=json"',
        '            req_title = urllib.request.Request(title_url + title_query)',
        '            req_title.add_header("User-Agent", "Mozilla/5.0")',
        '            with urllib.request.urlopen(req_title, timeout=5) as resp_title:',
        '                title_res = resp_title.read().decode("utf-8")',
        '            if title_res.strip():',
        '                title_data = json.loads(title_res)',
        '                items = title_data.get("response", {}).get("body", {}).get("items", {}).get("item", [])',
        '                if items:',
        '                    if isinstance(items, dict):',
        '                        items = [items]',
        '                    selected_title = items[0]',
        '                    if dong_name:',
        '                        for t in items:',
        '                            if match_dong(dong_name, t.get("dongNm", "")):',
        '                                selected_title = t',
        '                                break',
        '                    main_purp = selected_title.get("mainPurpsCdNm", "")',
        '                    bld_name = selected_title.get("bldNm", "")',
        '                    etc_purp = selected_title.get("etcPurps", "")',
        '                    apr = str(selected_title.get("useAprDay", "")).strip()',
        '                    if apr and len(apr) >= 4:',
        '                        target_build_year = int(apr[:4])',
        '            prop_type = classify_property_type(main_purp, bld_name, etc_purp)',
        '            type_names = {"1": "아파트", "2": "연립/다세대/빌라", "3": "오피스텔", "4": "단독/다가구"}',
        '            print(f" -> 부동산 유형 자동 판별 완료: [{type_names.get(prop_type, \'일반 부동산\')}]")',
        '            if prop_type == "4":',
        '                combined = main_purp + " " + etc_purp + " " + bld_name.lower()',
        '                if "다가구" in combined:',
        '                    target_house_type = "다가구"',
        '                elif "단독" in combined:',
        '                    target_house_type = "단독"',
        '            if ho_name:',
        '                print(f" -> [{ho_name}호] 전유부 면적 및 층수 조회 중...")',
        '                unit_details = get_expos_unit_details(addr_info["sigunguCd"], addr_info["bjdongCd"], addr_info["bun"], addr_info["ji"], ho_name, dong_name)',
        '                if unit_details:',
        '                    try:',
        '                        target_floor = int(re.sub(\'\\\\D\', \'\', str(unit_details.get("flrNo", "0"))))',
        '                    except:',
        '                        target_floor = 0',
        '                    target_area = unit_details.get("area", 0.0)',
        '                    print(f"    [자동 입력 완료] {ho_name}호 기준 층: {target_floor}층 / 전용면적: {target_area:.2f}㎡")',
        '        except Exception as e:',
        '            print(f" [!] 부동산 유형/대장 조회 중 오류 발생: {e}")',
        '    transactions = get_recent_transactions(addr_info["sigunguCd"], addr_info["bun"], addr_info["ji"], prop_type, addr_info.get("bjdongNm"), target_build_year, target_house_type)',
        '    if transactions:',
        '        address_name = clean_address',
        '        print_comparison_table(transactions, prop_type, target_floor, target_area, address_name, sigunguCd=addr_info["sigunguCd"], bun=addr_info["bun"], ji=addr_info["ji"], bjdong_nm=addr_info.get("bjdongNm"), target_build_year=target_build_year, target_house_type=target_house_type, save_report=pre_address_info is None)',
        '    else:',
        '        print(" [!] 최근 실거래 내역이 존재하지 않거나 가져오는데 실패했습니다.")',
        '    if not pre_address_info:',
        '        input("\\n메뉴로 돌아가려면 엔터를 누르세요...")',
        '',
        'if __name__ == "__main__":',
        '    if sys.platform == "win32":',
        '        sys.stdin.reconfigure(encoding="utf-8", errors="replace")',
        '        sys.stdout.reconfigure(encoding="utf-8", errors="replace")',
        '        while True:',
        '            try:',
        '                run_trade_viewer(None, None, None, None)',
        '            except KeyboardInterrupt:',
        '                break',
        '            except Exception as e:',
        '                print(f"오류 발생: {e}")'
    ]
    clean_lines.extend(run_trade_viewer_code)

    return '\n'.join(clean_lines)

def clean_building_viewer():
    p = r'D:\부동산업무\antigravity\consult_diary\scratch\중개수첩_오토봇.exe_extracted\PYZ.pyz_extracted\decompiled\building_viewer.py'
    raw_lines = open(p, 'r', encoding='utf-8', errors='ignore').read().splitlines()

    # 1. Split header and body (unindenting by 12 spaces)
    header_lines = raw_lines[:48]
    body_lines = []
    for line in raw_lines[53:]:
        if line.startswith('            '):
            body_lines.append(line[12:])
        elif line.strip() == '':
            body_lines.append('')
        else:
            body_lines.append(line.lstrip())

    lines = header_lines + body_lines

    # Find the start of def run_building_viewer and truncate everything after
    run_bv_idx = -1
    for idx, line in enumerate(lines):
        if line.startswith('def run_building_viewer'):
            run_bv_idx = idx
            break
    if run_bv_idx != -1:
        lines = lines[:run_bv_idx]

    # 2. format_member_name
    replace_block(lines, 'def format_member_name(name):', 'return f"{name} 공인중개사"', [
        'def format_member_name(name):',
        '    if not name:',
        '        return "중개"',
        '    if any(suffix in name for suffix in ("중개", "공인", "부동산", "방", "대표")):',
        '        return name',
        '    return f"{name} 중개"'
    ])

    # 3. Kakao, Land, LandUse, ApartmentAssessed Price APIs
    apis_block = [
        'def get_kakao_address_info(address_str):',
        '    url = "https://dapi.kakao.com/v2/local/search/address.json"',
        '    headers = {"Authorization": f"KakaoAK {KAKAO_API_KEY}"}',
        '    params = {"query": address_str}',
        '    try:',
        '        res = requests.get(url, headers=headers, params=params, timeout=5)',
        '        data = res.json()',
        '        if data.get("documents"):',
        '            doc = data["documents"][0]',
        '            addr = doc.get("address", {})',
        '            if not addr:',
        '                return None',
        '            b_code = addr.get("b_code", "")',
        '            h_code = addr.get("h_code", "")',
        '            code_to_use = b_code if len(b_code) >= 10 else h_code',
        '            if len(code_to_use) >= 10:',
        '                road_addr_val = ""',
        '                if doc.get("road_address"):',
        '                    road_addr_val = doc.get("road_address", {}).get("address_name", "")',
        '                return {',
        '                    "sigunguCd": code_to_use[:5],',
        '                    "bjdongCd": code_to_use[5:10],',
        '                    "bjdongNm": addr.get("region_3depth_name", ""),',
        '                    "bun": addr.get("main_address_no", ""),',
        '                    "ji": addr.get("sub_address_no", "0") or "0",',
        '                    "road_address": road_addr_val,',
        '                    "sidoNm": addr.get("region_1depth_name", ""),',
        '                    "sigunguNm": addr.get("region_2depth_name", "")',
        '                }',
        '        return None',
        '    except Exception as e:',
        '        print(f"카카오 API 에러: {e}")',
        '        return None',
        '',
        'def get_vworld_land_info(vworld_key, pnu):',
        '    url = f"https://api.vworld.kr/ned/data/getLandCharacteristics?key={vworld_key}&domain=http://localhost&pnu={pnu}&format=json&numOfRows=10&pageNo=1"',
        '    req = urllib.request.Request(url)',
        '    req.add_header("Referer", "http://localhost")',
        '    try:',
        '        with urllib.request.urlopen(req, timeout=5) as resp:',
        '            data = json.loads(resp.read().decode("utf-8"))',
        '            items = data.get("landCharacteristicss", {}).get("field", [])',
        '            if not items:',
        '                items = data.get("response", {}).get("landCharacteristicss", {}).get("field", [])',
        '        if items:',
        '            if isinstance(items, dict):',
        '                items = [items]',
        '            return items[0]',
        '        return None',
        '    except Exception as e:',
        '        print(f"공시지가 조회 에러: {e}")',
        '        return None',
        '',
        'def get_vworld_land_use_info(vworld_key, pnu, sigungu_cd):',
        '    url = f"https://api.vworld.kr/ned/data/getLandUseAttr?key={vworld_key}&domain=http://localhost&pnu={pnu}&format=json&numOfRows=100&pageNo=1"',
        '    req = urllib.request.Request(url)',
        '    req.add_header("Referer", "http://localhost")',
        '    result = {',
        '        "moatown": False,',
        '        "moatown_name": "",',
        '        "redev": False,',
        '        "redev_name": "",',
        '        "permit": False,',
        '        "permit_name": "",',
        '        "regulated": False,',
        '        "regulated_name": ""',
        '    }',
        '    regulated_districts = {',
        '        "11680": "강남구 (투기과열지구/조정대상지역)",',
        '        "11650": "서초구 (투기과열지구/조정대상지역)",',
        '        "11710": "송파구 (투기과열지구/조정대상지역)",',
        '        "11170": "용산구 (투기과열지구/조정대상지역)"',
        '    }',
        '    if sigungu_cd in regulated_districts:',
        '        result["regulated"] = True',
        '        result["regulated_name"] = regulated_districts[sigungu_cd]',
        '    try:',
        '        with urllib.request.urlopen(req, timeout=5) as resp:',
        '            data = json.loads(resp.read().decode("utf-8"))',
        '            items = data.get("landUses", {}).get("field", [])',
        '            if not items:',
        '                items = data.get("response", {}).get("landUses", {}).get("field", [])',
        '        if items:',
        '            if isinstance(items, dict):',
        '                items = [items]',
        '            moatown_list = []',
        '            redev_list = []',
        '            permit_list = []',
        '            for item in items:',
        '                name = item.get("prposAreaDstrcCodeNm", "")',
        '                if not name:',
        '                    continue',
        '                if any(kw in name for kw in ("소규모주택정비 관리지역", "소규모주택정비관리지역")) or ("소규모주택" in name and "관리지역" in name):',
        '                    moatown_list.append(name)',
        '                if any(kw in name for kw in ("정비구역", "재개발", "재건축", "도시환경정비")):',
        '                    redev_list.append(name)',
        '                if "토지거래계약에관한허가구역" in name or "토지거래허가" in name:',
        '                    permit_list.append(name)',
        '            if moatown_list:',
        '                result["moatown"] = True',
        '                result["moatown_name"] = ", ".join(list(set(moatown_list)))',
        '            if redev_list:',
        '                result["redev"] = True',
        '                result["redev_name"] = ", ".join(list(set(redev_list)))',
        '            if permit_list:',
        '                result["permit"] = True',
        '                result["permit_name"] = ", ".join(list(set(permit_list)))',
        '        return result',
        '    except Exception as e:',
        '        print(f"토지이용계획 조회 에러: {e}")',
        '        return result',
        '',
        'def get_vworld_apartment_house_price(vworld_key, pnu, dong_name, ho_name):',
        '    url = f"https://api.vworld.kr/ned/data/getApartHousingPriceAttr?key={vworld_key}&domain=http://localhost&pnu={pnu}&format=json&numOfRows=1000&pageNo=1"',
        '    req = urllib.request.Request(url)',
        '    req.add_header("Referer", "http://localhost")',
        '    try:',
        '        with urllib.request.urlopen(req, timeout=5) as resp:',
        '            data = json.loads(resp.read().decode("utf-8"))',
        '            items = data.get("apartHousingPrices", {}).get("field", [])',
        '            if not items:',
        '                items = data.get("response", {}).get("apartHousingPrices", {}).get("field", [])',
        '        if items:',
        '            if isinstance(items, dict):',
        '                items = [items]',
        '            def match_part(target, item):',
        '                if not target:',
        '                    return True',
        '                if not item:',
        '                    return False',
        '                t_str = str(target).strip().lower()',
        '                i_str = str(item).strip().lower()',
        '                if t_str == i_str:',
        '                    return True',
        '                t_clean = t_str.replace("호", "").replace("동", "")',
        '                i_clean = i_str.replace("호", "").replace("동", "")',
        '                if t_clean == i_clean:',
        '                    return True',
        '                t_num = re.sub("[^0-9]", "", t_clean)',
        '                i_num = re.sub("[^0-9]", "", i_clean)',
        '                if t_num and i_num:',
        '                    return int(t_num) == int(i_num)',
        '                return False',
        '',
        '            matched_items = []',
        '            for item in items:',
        '                item_dong = item.get("dongNm", "") or ""',
        '                item_ho = item.get("hoNm", "") or ""',
        '                if ho_name:',
        '                    if match_part(ho_name, item_ho):',
        '                        if dong_name:',
        '                            if match_part(dong_name, item_dong):',
        '                                matched_items.append(item)',
        '                        else:',
        '                            matched_items.append(item)',
        '                else:',
        '                    matched_items.append(item)',
        '            if matched_items:',
        '                items_sorted = sorted(matched_items, key=lambda x: x.get("stdrYear", ""), reverse=True)',
        '                for item in items_sorted:',
        '                    price_val = item.get("pblntfPc")',
        '                    year_val = item.get("stdrYear")',
        '                    if price_val and year_val:',
        '                        return {"year": year_val, "price": int(price_val)}',
        '        return None',
        '    except Exception as e:',
        '        print(f"공동주택가격 조회 에러: {e}")',
        '        return None',
        '',
        'def format_assessed_price(val):',
        '    if not val:',
        '        return "정보없음"',
        '    if val >= 100_000_000:',
        '        eok = val // 100_000_000',
        '        man = val % 100_000_000 // 10_000',
        '        if man > 0:',
        '            return f"{eok}억 {man:,}만원"',
        '        return f"{eok}억원"',
        '    man = val // 10_000',
        '    return f"{man:,}만원"',
        '',
        'def get_building_title_info(sigungu, bjdong, bun, ji):'
    ]
    replace_block(lines, 'def get_kakao_address_info(address_str):', 'def get_building_title_info(sigungu, bjdong, bun, ji):', apis_block)

    # 4. Three building info helpers: get_building_title_info, get_expos_info_list, get_building_floor_info
    helpers_block = [
        'def get_building_title_info(sigungu, bjdong, bun, ji):',
        '    bun_str = str(bun).zfill(4) if bun else "0000"',
        '    ji_str = str(ji).zfill(4) if ji else "0000"',
        '    url = "https://apis.data.go.kr/1613000/BldRgstHubService/getBrTitleInfo"',
        '    query = f"?serviceKey={GOV_API_KEY}&sigunguCd={sigungu}&bjdongCd={bjdong}&platGbCd=0&bun={bun_str}&ji={ji_str}&numOfRows=10&pageNo=1&_type=json"',
        '    try:',
        '        req = urllib.request.Request(url + query)',
        '        req.add_header("User-Agent", "Mozilla/5.0")',
        '        req.add_header("Accept", "application/json, text/plain, */*")',
        '        with urllib.request.urlopen(req, timeout=5) as response:',
        '            res_text = response.read().decode("utf-8")',
        '        if not res_text.strip():',
        '            return None',
        '        json_data = json.loads(res_text)',
        '        items = json_data.get("response", {}).get("body", {}).get("items", {}).get("item", [])',
        '        if not items:',
        '            return None',
        '        if isinstance(items, dict):',
        '            return [items]',
        '        return items',
        '    except Exception as e:',
        '        print(f"get_building_title_info 에러: {e}")',
        '        return None',
        '',
        'def get_expos_info_list(sigungu, bjdong, bun, ji):',
        '    bun_str = str(bun).zfill(4) if bun else "0000"',
        '    ji_str = str(ji).zfill(4) if ji else "0000"',
        '    url = "https://apis.data.go.kr/1613000/BldRgstHubService/getBrExposInfo"',
        '    query = f"?serviceKey={GOV_API_KEY}&sigunguCd={sigungu}&bjdongCd={bjdong}&platGbCd=0&bun={bun_str}&ji={ji_str}&numOfRows=100&pageNo=1&_type=json"',
        '    try:',
        '        req = urllib.request.Request(url + query)',
        '        req.add_header("User-Agent", "Mozilla/5.0")',
        '        req.add_header("Accept", "application/json, text/plain, */*")',
        '        with urllib.request.urlopen(req, timeout=5) as response:',
        '            res_text = response.read().decode("utf-8")',
        '        if not res_text.strip():',
        '            return None',
        '        json_data = json.loads(res_text)',
        '        items = json_data.get("response", {}).get("body", {}).get("items", {}).get("item", [])',
        '        if not items:',
        '            return None',
        '        if isinstance(items, dict):',
        '            return [items]',
        '        return items',
        '    except Exception as e:',
        '        print(f"get_expos_info_list 에러: {e}")',
        '        return None',
        '',
        'def get_building_floor_info(sigungu, bjdong, bun, ji):',
        '    bun_str = str(bun).zfill(4) if bun else "0000"',
        '    ji_str = str(ji).zfill(4) if ji else "0000"',
        '    url = "https://apis.data.go.kr/1613000/BldRgstHubService/getBrFlrOulnInfo"',
        '    query = f"?serviceKey={GOV_API_KEY}&sigunguCd={sigungu}&bjdongCd={bjdong}&platGbCd=0&bun={bun_str}&ji={ji_str}&numOfRows=100&pageNo=1&_type=json"',
        '    try:',
        '        req = urllib.request.Request(url + query)',
        '        req.add_header("User-Agent", "Mozilla/5.0")',
        '        req.add_header("Accept", "application/json, text/plain, */*")',
        '        with urllib.request.urlopen(req, timeout=5) as response:',
        '            res_text = response.read().decode("utf-8")',
        '        if not res_text.strip():',
        '            return None',
        '        json_data = json.loads(res_text)',
        '        items = json_data.get("response", {}).get("body", {}).get("items", {}).get("item", [])',
        '        if not items:',
        '            return None',
        '        if isinstance(items, dict):',
        '            return [items]',
        '        return items',
        '    except Exception as e:',
        '        print(f"get_building_floor_info 에러: {e}")',
        '        return None',
        ''
    ]
    replace_block(lines, 'def get_building_title_info(sigungu, bjdong, bun, ji):', 'def mask_address_string(addr_str):', helpers_block)

    # 5. bld_info_data table row format logic
    replace_block(lines, 'story.append(Paragraph("■ [기본 건축물 정보]", h2_style))', 'info_table = Table(bld_info_data, colWidths=[100, 150, 100, 150])', [
        '        story.append(Paragraph("■ [기본 건축물 정보]", h2_style))',
        '        bld_type_label = "집합건물" if bld_data["is_jibbap"] else "일반건물"',
        '        bld_info_data = [',
        '            [Paragraph("<b>건물 유형</b>", label_style), Paragraph(bld_type_label, value_style),',
        '             Paragraph("<b>대지면적</b>", label_style), Paragraph(f"{bld_data[\'plat_area\']} ㎡", value_style)],',
        '            [Paragraph("<b>주용도</b>", label_style), Paragraph(bld_data["main_purp"], value_style),',
        '             Paragraph("<b>건물구조</b>", label_style), Paragraph(bld_data["structure"], value_style)],',
        '            [Paragraph("<b>건축면적</b>", label_style), Paragraph(f"{bld_data[\'arch_area\']} ㎡", value_style),',
        '             Paragraph("<b>연면적</b>", label_style), Paragraph(f"{bld_data[\'tot_area\']} ㎡ (용적률산정: {bld_data[\'vl_rat_tot_area\']} ㎡)", value_style)],',
        '            [Paragraph("<b>층수</b>", label_style), Paragraph(f"지상 {bld_data[\'grnd_cnt\']}층 / 지하 {bld_data[\'ugrnd_cnt\']}층", value_style),',
        '             Paragraph("<b>세대/가구수</b>", label_style), Paragraph(f"공동주택 {bld_data[\'hhld\']}세대 / 다가구 {bld_data[\'fmly\']}가구", value_style)],',
        '            [Paragraph("<b>총 주차대수</b>", label_style), Paragraph(f"{bld_data[\'parking\']} 대", value_style),',
        '             Paragraph("<b>사용승인일</b>", label_style), Paragraph(bld_data[\'apr_day\'], value_style)],',
        '            [Paragraph("<b>위반 여부</b>", label_style), Paragraph(bld_data[\'viol_str\'], value_style),',
        '             Paragraph("<b>엘리베이터</b>", label_style), Paragraph(elvt_pdf_val, value_style)]',
        '        ]',
        '        if bld_data.get("room_count_label"):',
        '            bld_info_data.append([Paragraph("<b>방 개수</b>", label_style), Paragraph(bld_data["room_count_label"], value_style), Paragraph("", label_style), Paragraph("", value_style)])',
        '        info_table = Table(bld_info_data, colWidths=[100, 150, 100, 150])'
    ])

    # 6. land_price_data table creation
    replace_block(lines, 'if not bld_data["is_jibbap"]:', 'land_price_data = bld_data["is_jibbap"] or [Paragraph(land_price_str, value_style),', [
        '        if bld_data["is_jibbap"]:',
        '            land_price_data = [',
        '                [Paragraph("<b>개별공시지가</b>", label_style), Paragraph(land_price_str, value_style),',
        '                 Paragraph("<b>공동주택가격</b>", label_style), Paragraph(house_price_str, value_style)]',
        '            ]',
        '        else:',
        '            land_price_data = [',
        '                [Paragraph("<b>개별공시지가</b>", label_style), Paragraph(land_price_str, value_style),',
        '                 Paragraph("<b>개별주택가격</b>", label_style), Paragraph(house_price_str, value_style)]',
        '            ]'
    ])

    # 7. reg_table_data table creation
    replace_block(lines, 'reg = bld_data["reg_info"]', 'reg_table_data = ["⚠️ 지정됨"', [
        '        dev_status = "⚪ 해당없음"',
        '        if reg["moatown"]:',
        '            dev_status = f"⚠️ 모아타운 ({reg[\'moatown_name\']})"',
        '        elif reg["redev"]:',
        '            dev_status = f"⚠️ 정비구역 ({reg[\'redev_name\']})"',
        '',
        '        reg_status = "⚪ 비규제지역"',
        '        if reg["permit"]:',
        '            reg_status = f"⚠️ 토지거래허가 ({reg[\'permit_name\']})"',
        '        elif reg["regulated"]:',
        '            reg_status = f"⚠️ 규제지역 ({reg[\'regulated_name\']})"',
        '',
        '        reg_table_data = [',
        '            [Paragraph("<b>개발구역지정</b>", label_style), Paragraph(dev_status, value_style),',
        '             Paragraph("<b>규제 및 허가</b>", label_style), Paragraph(reg_status, value_style)]',
        '        ]'
    ])

    # 8. ho_table_data unit area and viol status details
    replace_block(lines, 'if hd.get("area"):', 'apt_price_str, value_style)]]', [
        '            pyung_area = "정보없음"',
        '            if hd.get("area"):',
        '                a = float(hd["area"])',
        '                pyung_area = f"{a:.2f}㎡ (약 {round(a * 0.3025, 1)}평)"',
        '            supply_area = "정보없음"',
        '            if hd.get("supply_area"):',
        '                sa = float(hd["supply_area"])',
        '                supply_area = f"{sa:.2f}㎡ (약 {round(sa * 0.3025, 1)}평)"',
        '            land_share_str = "정보없음"',
        '            if hd.get("land_share"):',
        '                l_area = float(hd["land_share"])',
        '                land_share_str = f"{l_area:.2f} ㎡ ({round(l_area * 0.3025, 1)}평)"',
        '            apt_price_str = "정보없음"',
        '            if hd.get("apt_price"):',
        '                price_val = hd["apt_price"]',
        '                formatted_p = format_assessed_price(price_val)',
        '                price_126 = int(price_val * 1.26)',
        '                formatted_126 = format_assessed_price(price_126)',
        '                apt_price_str = f"{formatted_p} (126%: {formatted_126})"',
        '                if hd.get("apt_price_year"):',
        '                    apt_price_str = f"{hd[\'apt_price_year\']}년 기준 {apt_price_str}"',
        '            viol_status = "⚠️ 위반건축물" if hd.get("viol_yn") == "Y" else "정상 (위반 없음)"',
        '            ho_table_data = [',
        '                [Paragraph("<b>해당 층수</b>", label_style), Paragraph(f"{hd[\'flr_no\']}층", value_style), Paragraph("<b>위반 여부</b>", label_style), Paragraph(viol_status, value_style)],',
        '                [Paragraph("<b>전용면적</b>", label_style), Paragraph(pyung_area, value_style), Paragraph("<b>공급면적</b>", label_style), Paragraph(supply_area, value_style)],',
        '                [Paragraph("<b>대지지분</b>", label_style), Paragraph(land_share_str, value_style), Paragraph("<b>공동주택가격</b>", label_style), Paragraph(apt_price_str, value_style)]',
        '            ]'
    ])

    # 9. safe_addr joined string logic
    replace_block(lines, '[c for c in address if not c in (" ", "-", "_")]', 'safe_addr = ##ERROR##("".join).strip();', [
        '    safe_addr = "".join([c for c in address if c not in (" ", "-", "_")]).strip();'
    ])

    # 10. building information lines.append block
    func_idx = -1
    for idx, line in enumerate(lines):
        if 'def save_building_report(address, bld_data):' in line:
            func_idx = idx
            break
    
    replace_block(lines, 'if bld_data["is_jibbap"]:', '용도지역 : {"정보없음"}', [
        '    bld_type_str = "집합건물 (공동주택/아파트/오피스텔 등)" if bld_data["is_jibbap"] else "일반건물 (단독/다가구/상가주택 등)"',
        '    lines.append(f"  • 건물 유형: {bld_type_str}")',
        '    ',
        '    masked_bld_nm = bld_data.get("bld_nm") or "정보없음"',
        '    dong_nm_suffix = f" / {bld_data[\'dong_nm\']}동" if bld_data.get("dong_nm") else ""',
        '    lines.append(f"  • 건물명/동: {masked_bld_nm}{dong_nm_suffix}")',
        '    lines.append(f"  • 대지면적 : {bld_data[\'plat_area\']} ㎡")',
        '    lines.append(f"  • 지목     : {bld_data.get(\'lndcgr\') or \'정보없음\'}")',
        '    lines.append(f"  • 용도지역 : {bld_data.get(\'use_zone\') or \'정보없음\'}")'
    ], start_from=func_idx)

    # Clean up lines
    clean_lines = []
    for line in lines:
        if line.strip().startswith('def run_building_viewer'):
            break
        if '__exit__(None, None, None)' in line or '##ERROR##(None, None, None)' in line:
            continue
        if 'urllib.request.urlopen(req).__exit__' in line:
            clean_lines.append(line.replace('urllib.request.urlopen(req).__exit__', 'None'))
            continue
        if 'str(ji).zfill(4)(urllib.request.urlopen(req), None, None, None)' in line:
            continue
        clean_lines.append(line)

    # 11. Reconstruct run_building_viewer and add __main__ entry point
    run_building_viewer_code = [
        'def run_building_viewer():',
        '    try:',
        '        print("\\n============================================================")',
        '        print("      건물 정보 조회 및 물건 분석 (CMA 보고서)      ")',
        '        print("============================================================")',
        '        print("  ※ [안내] 일부 공공데이터포털 시스템 점검 시 정보가 누락될 수 있으며,")',
        '        print("            그 외의 경우 정상 조회됩니다.")',
        '        print("  ------------------------------------------------------------")',
        '        print("  조회할 주소를 입력하시면 건축물대장(표제부/전유부), 공시지가,")',
        '        print("  그리고 해당 지번의 최근 실거래(매매/임대차) 내역을 일괄 조회하여 보여줍니다.")',
        '        print("  (메뉴로 돌아가려면 \'q\' 또는 엔터를 입력하세요)")',
        '        print("------------------------------------------------------------")',
        '        address = input("\\n[입력] 조회할 건물 주소 (예: 성산동 138-4 402호): ").strip()',
        '        if not address or address.lower() == "q":',
        '            return',
        '        from trade_viewer import parse_address_and_ho, get_expos_unit_details, classify_property_type, get_recent_transactions, print_comparison_table, match_dong, print_empty_transactions_explanation',
        '        clean_address, dong_name, ho_name = parse_address_and_ho(address)',
        '        bld_nm = ""',
        '        dong_nm = ""',
        '        is_jibbap = False',
        '        plat_area_val = "0"',
        '        land_info = None',
        '        land_price_info = None',
        '        hhld = 0',
        '        fmly = 0',
        '        parking = 0',
        '        apr_str = "정보없음"',
        '        viol = "N"',
        '        viol_str = "정상 (위반 없음)"',
        '        print(" -> 주소 변환 및 검색 중...")',
        '        addr_info = get_kakao_address_info(clean_address)',
        '        if not addr_info:',
        '            print(" [!] 주소 변환 실패! 주소를 정확히 입력하셨는지 확인해 주세요.")',
        '            return',
        '        display_road = addr_info.get("road_address") or "도로명 없음"',
        '        print(f" -> 주소 확인: {clean_address} ({display_road})")',
        '        print(" -> 건축물 표제부 조회 중...")',
        '        titles = get_building_title_info(addr_info["sigunguCd"], addr_info["bjdongCd"], addr_info["bun"], addr_info["ji"])',
        '        if not titles:',
        '            print(" [!] 등록된 표제부(건물 정보) 데이터가 없습니다. (단독 필지 또는 미등록 대지)")',
        '            return',
        '        selected_title = titles[0]',
        '        if dong_name:',
        '            for t in titles:',
        '                if match_dong(dong_name, t.get("dongNm", "")):',
        '                    selected_title = t',
        '                    break',
        '        main_purp = selected_title.get("mainPurpsCdNm", "")',
        '        bld_name = selected_title.get("bldNm", "")',
        '        etc_purp = selected_title.get("etcPurps", "")',
        '        prop_type = classify_property_type(main_purp, bld_name, etc_purp)',
        '        reg_gb_cd = str(selected_title.get("regstrGbCd", "")).strip()',
        '        reg_gb_nm = str(selected_title.get("regstrGbCdNm", "")).strip()',
        '        if reg_gb_cd:',
        '            is_jibbap = (reg_gb_cd == "2" or reg_gb_nm == "집합")',
        '        else:',
        '            is_jibbap = prop_type in ("1", "2", "3")',
        '        bun_val = str(addr_info["bun"]).zfill(4) if addr_info.get("bun") else "0000"',
        '        ji_val = str(addr_info["ji"]).zfill(4) if addr_info.get("ji") else "0000"',
        '        pnu = f"{addr_info[\'sigunguCd\']}{addr_info[\'bjdongCd\']}1{bun_val}{ji_val}"',
        '        vworld_key = "80194C85-0EE3-3220-A3C1-3268AD8756B9"',
        '        land_share = ""',
        '        if ho_name:',
        '            try:',
        '                from serve_auto_upload import get_vworld_land_share',
        '                land_share = get_vworld_land_share(vworld_key, pnu, "", ho_name)',
        '            except Exception as e:',
        '                print(f"대지지분 조회 에러: {e}")',
        '        print("\\n═══════════════════════════════════════════════════════")',
        '        bld_nm = selected_title.get("bldNm", "").strip()',
        '        dong_nm = selected_title.get("dongNm", "").strip()',
        '        bld_tag = f" ({bld_nm})" if bld_nm else ""',
        '        dong_tag = f" / {dong_nm}동" if dong_nm else ""',
        '        print(f" [건물대장] {clean_address}{bld_tag}{dong_tag}")',
        '        print("═══════════════════════════════════════════════════════")',
        '        land_info = get_vworld_land_info(vworld_key, pnu)',
        '        plat_area_val = str(selected_title.get("platArea", "0")).strip()',
        '        try:',
        '            plat_area_float = float(plat_area_val)',
        '        except:',
        '            plat_area_float = 0.0',
        '        if plat_area_float == 0.0 and land_info and land_info.get("area") and float(land_info["area"]) > 0:',
        '            plat_area_val = land_info["area"]',
        '        print(f"  • 대지면적  : {plat_area_val} ㎡")',
        '        if land_info:',
        '            if land_info.get("lndcgr"):',
        '                print(f"  • 지목      : {land_info[\'lndcgr\']}")',
        '            if land_info.get("use_zone"):',
        '                print(f"  • 용도지역  : {land_info[\'use_zone\']}")',
        '        land_price_info = get_vworld_land_price(vworld_key, pnu)',
        '        if land_price_info:',
        '            p_m2 = land_price_info["price"]',
        '            p_py = round(p_m2 / 0.3025)',
        '            print(f"  • 공시지가  : {land_price_info[\'year\']}년 기준 ㎡당 {p_m2:,}원 (평당 약 {p_py:,}원)")',
        '        print(f"  • 건축면적  : {selected_title.get(\'archArea\', \'0\')} ㎡")',
        '        print(f"  • 연면적    : {selected_title.get(\'totArea\', \'0\')} ㎡ (용적률산정연면적: {selected_title.get(\'vlRatEstTotArea\', \'0\')} ㎡)")',
        '        print(f"  • 건물구조  : {selected_title.get(\'strctCdNm\', \'정보없음\')}")',
        '        print(f"  • 주용도    : {selected_title.get(\'mainPurpsCdNm\', \'정보없음\')}")',
        '        print(f"  • 층수      : 지상 {selected_title.get(\'grndFlrCnt\', \'0\')}층 / 지하 {selected_title.get(\'ugrndFlrCnt\', \'0\')}층")',
        '        try:',
        '            hhld = int(selected_title.get("hhldCnt", 0) or 0)',
        '        except:',
        '            hhld = 0',
        '        try:',
        '            fmly = int(selected_title.get("fmlyCnt", 0) or 0)',
        '        except:',
        '            fmly = 0',
        '        max_units = max(hhld, fmly)',
        '        print(f"  • 세대/가구 : 공동주택 {hhld}세대 / 다가구 {fmly}가구 (총 {max_units}호실)")',
        '        parking = 0',
        '        for p_type in ("indrAutoUtcnt", "indrMechUtcnt", "oudrAutoUtcnt", "oudrMechUtcnt"):',
        '            try:',
        '                val = selected_title.get(p_type, 0)',
        '                parking += int(val or 0)',
        '            except:',
        '                pass',
        '        print(f"  • 총 주차대수: {parking} 대")',
        '        apr = str(selected_title.get("useAprDay", "")).strip()',
        '        apr_str = "정보없음"',
        '        if apr and len(apr) == 8:',
        '            apr_str = f"{apr[:4]}년 {apr[4:6]}월 {apr[6:8]}일"',
        '        elif apr:',
        '            apr_str = apr',
        '        print(f"  • 사용승인일: {apr_str}")',
        '        target_build_year = None',
        '        if apr and len(apr) >= 4:',
        '            try:',
        '                target_build_year = int(apr[:4])',
        '            except:',
        '                pass',
        '        target_house_type = None',
        '        if prop_type == "4":',
        '            combined = main_purp + " " + etc_purp + " " + bld_name.lower()',
        '            if "다가구" in combined:',
        '                target_house_type = "다가구"',
        '            elif "단독" in combined:',
        '                target_house_type = "단독"',
        '        viol = str(selected_title.get("violBldYn", "N")).strip()',
        '        viol_str = "⚠️ 위반건축물 지정!!" if viol == "Y" else "정상 (위반 없음)"',
        '        print(f"  • 위반 여부 : {viol_str}")',
        '        try:',
        '            ride_elvt = int(selected_title.get("rideUseElvtCnt", 0) or 0)',
        '        except:',
        '            ride_elvt = 0',
        '        try:',
        '            emgen_elvt = int(selected_title.get("emgenUseElvtCnt", 0) or 0)',
        '            total_elvt = ride_elvt + emgen_elvt',
        '        except:',
        '            pass',
        '        try:',
        '            grnd_cnt_int = int(selected_title.get("grndFlrCnt", 0) or 0)',
        '        except:',
        '            grnd_cnt_int = 0',
        '        if total_elvt > 0:',
        '            elvt_str = f"있음 (승용 {ride_elvt}대 / 비상용 {emgen_elvt}대)"',
        '        elif grnd_cnt_int >= 4:',
        '            elvt_str = "❌ 없음 (⚠️ 4층 이상 엘리베이터 없음 - 감가요인)"',
        '        else:',
        '            elvt_str = "없음"',
        '        print(f"  • 엘리베이터: {elvt_str}")',
        '        if not is_jibbap:',
        '            indiv_house_price = get_vworld_individual_house_price(vworld_key, pnu)',
        '            if indiv_house_price:',
        '                price_val = indiv_house_price["price"]',
        '                formatted_p = format_assessed_price(price_val)',
        '                price_126 = int(price_val * 1.26)',
        '                formatted_126 = format_assessed_price(price_126)',
        '                print(f"  • 주택공시가격: {indiv_house_price[\'year\']}년 기준 {formatted_p} (126%: {formatted_126})")',
        '        print(" -> 토지이용규제 및 개발구역(모아타운/정비구역/허가구역) 정보 조회 중...")',
        '        reg_info = get_vworld_land_use_info(vworld_key, pnu, addr_info["sigunguCd"])',
        '        if reg_info:',
        '            print("───────────────────────────────────────────────────────")',
        '            print("  [ 토지규제 및 구역지정 정보 ]")',
        '            dev_status = "⚪ 해당없음"',
        '            if reg_info["moatown"]:',
        '                dev_status = f"⚠️ 모아타운지정 ({reg_info[\'moatown_name\']})"',
        '            elif reg_info["redev"]:',
        '                dev_status = f" 정비구역지정 ({reg_info[\'redev_name\']})"',
        '            print(f"  • 개발구역지정 : {dev_status}")',
        '            reg_status = "⚪ 비규제지역"',
        '            if reg_info["permit"]:',
        '                reg_status = f"⚠️ 토지거래허가구역 ({reg_info[\'permit_name\']})"',
        '            elif reg_info["regulated"]:',
        '                reg_status = f"⚠️ 규제지역 ({reg_info[\'regulated_name\']})"',
        '            print(f"  • 규제 및 허가 : {reg_status}")',
        '        print("═══════════════════════════════════════════════════════")',
        '        target_floor = None',
        '        target_area = None',
        '        unit_info = None',
        '        floor_map = {}',
        '        expos_list_count = 0',
        '        if is_jibbap:',
        '            if ho_name:',
        '                print(f"\\n -> 요청하신 [{ho_name}호] 전유부 상세 정보 조회 중...")',
        '                unit_info = get_expos_unit_details(addr_info["sigunguCd"], addr_info["bjdongCd"], addr_info["bun"], addr_info["ji"], ho_name, dong_name)',
        '            print("\\n -> 전유부(가구/호수 리스트) 조회 중...")',
        '            expos_list = get_expos_info_list(addr_info["sigunguCd"], addr_info["bjdongCd"], addr_info["bun"], addr_info["ji"])',
        '            if expos_list:',
        '                distinct_dongs = set((item.get("dongNm", "").strip() for item in expos_list))',
        '                if dong_name and len(distinct_dongs) > 1:',
        '                    print("--------------------------------------------------")',
        '                    dongs_str = ", ".join(sorted(list(distinct_dongs)))',
        '                    print(f"  [참고] 이 지번에는 여러 개의 동({dongs_str})이 존재합니다.")',
        '                    print("         정확한 호수 구성을 확인하려면 동 정보(예: 101동)를 입력해 주세요.")',
        '                    print("--------------------------------------------------")',
        '                else:',
        '                    filtered_count = 0',
        '                    for item in expos_list:',
        '                        item_dong = item.get("dongNm", "") or ""',
        '                        if dong_name and not match_dong(dong_name, item_dong):',
        '                            continue',
        '                        flr = str(item.get("flrNo", "")).strip()',
        '                        ho = str(item.get("hoNm", "")).strip()',
        '                        if not flr or not ho:',
        '                            continue',
        '                        if flr not in floor_map:',
        '                            floor_map[flr] = set()',
        '                        floor_map[flr].add(ho)',
        '                        filtered_count += 1',
        '                    expos_list_count = filtered_count',
        '                    print("--------------------------------------------------")',
        '                    dong_desc = f" [{dong_name}동]" if dong_name else ""',
        '                    print(f"  [호수별 구성]{dong_desc} 총 {filtered_count}개 전유부분 등록됨")',
        '                    sorted_floors = sorted(floor_map.keys(), key=(lambda x: int(re.sub("[^0-9-]", "", x)) if re.sub("[^0-9-]", "", x) else 0))',
        '                    for flr in sorted_floors:',
        '                        hos = sorted(list(floor_map[flr]))',
        '                        hos_str = ", ".join(hos)',
        '                        print(f"   • {flr}층: {hos_str}")',
        '                    print("--------------------------------------------------")',
        '            else:',
        '                print("  [참고] 등록된 개별 호수 구성(전유부분)이 없습니다.")',
        '        else:',
        '            print("\\n -> 일반건축물 층별 면적(개요) 정보 조회 중...")',
        '            floors = get_building_floor_info(addr_info["sigunguCd"], addr_info["bjdongCd"], addr_info["bun"], addr_info["ji"])',
        '            if floors:',
        '                print("--------------------------------------------------")',
        '                print("   [ 건축물대장 층별 면적 및 용도 ]")',
        '                print("--------------------------------------------------")',
        '                def get_floor_sort_key(f):',
        '                    flr_no_str = str(f.get("flrNo", "0")).strip()',
        '                    flr_gb = f.get("flrGbCdNm", "") or ""',
        '                    try:',
        '                        val = int(re.sub("[^0-9-]", "", flr_no_str))',
        '                        if "지하" in flr_gb:',
        '                            return -100 + val',
        '                        elif "옥탑" in flr_gb:',
        '                            return 100 + val',
        '                        return val',
        '                    except:',
        '                        return 0',
        '                sorted_floors = sorted(floors, key=get_floor_sort_key)',
        '                for f in sorted_floors:',
        '                    flr_gb = f.get("flrGbCdNm", "") or ""',
        '                    flr_no = f.get("flrNo", "") or ""',
        '                    flr_desc = f"{flr_gb} {flr_no}".strip()',
        '                    structure = f.get("strctCdNm", "") or "정보없음"',
        '                    main_purps = f.get("mainPurpsCdNm", "") or "정보없음"',
        '                    area_val = f.get("area", "0")',
        '                    try:',
        '                        area_float = float(area_val)',
        '                    except:',
        '                        area_float = 0.0',
        '                    pyung = round(area_float * 0.3025, 1)',
        '                    area_str = f"{area_float:.2f} ㎡ ({pyung}평)"',
        '                    print(f"  • {flr_desc}: {main_purps} | {area_str} | {structure}")',
        '                print("--------------------------------------------------")',
        '            else:',
        '                print("  [참고] 등록된 층별 개요 정보가 없습니다.")',
        '            print("\\n -> 일반건축물 토지대장 및 지분 정보 조회 중...")',
        '            url_lda = f"https://api.vworld.kr/ned/data/ldaregList?key={vworld_key}&domain=http://localhost&pnu={pnu}&format=json&numOfRows=100&pageNo=1"',
        '            req_lda = urllib.request.Request(url_lda)',
        '            req_lda.add_header("Referer", "http://localhost")',
        '            try:',
        '                with urllib.request.urlopen(req_lda, timeout=5) as resp_lda:',
        '                    lda_data = json.loads(resp_lda.read().decode("utf-8"))',
        '                    items = lda_data.get("ldaregVOList", {}).get("ldaregVOList", [])',
        '            except Exception as e:',
        '                print(f"토지대장 조회 에러: {e}")',
        '        print("\\n==================================================")',
        '        cma_choice = input("[입력] 물건 분석(CMA) 및 시세 브리핑 보고서 생성을 진행하시겠습니까? (y/n) [기본값: n]: ").strip().lower()',
        '        if cma_choice != "y":',
        '            print(" -> 물건 분석을 진행하지 않고 종료합니다. (보고서가 저장되지 않습니다)")',
        '            print("═══════════════════════════════════════════════════════")',
        '            return',
        '        if not is_jibbap and ho_name:',
        '            print("\\n [안내] 해당 건물은 일반건축물이지만 호실이 지정되어 있어 집합건축물(호별대장)처럼 분석합니다.")',
        '            unit_info = get_expos_unit_details(addr_info["sigunguCd"], addr_info["bjdongCd"], addr_info["bun"], addr_info["ji"], ho_name, dong_name)',
        '        elif is_jibbap and not ho_name:',
        '            print("\\n [안내] 해당 건물은 집합건축물(호별대장 있음)이지만 호실이 지정되지 않았습니다.")',
        '            ho_input = input("[입력] 분석을 진행할 호실 번호를 입력해 주세요 (예: 201호, 건너뜀 시 엔터): ").strip()',
        '            if ho_input:',
        '                ho_name = ho_input.replace("호", "").strip()',
        '                print(f" -> 요청하신 [{ho_name}호] 전유부 상세 정보 조회 중...")',
        '                unit_info = get_expos_unit_details(addr_info["sigunguCd"], addr_info["bjdongCd"], addr_info["bun"], addr_info["ji"], ho_name, dong_name)',
        '        if unit_info:',
        '            print("--------------------------------------------------")',
        '            print(f"   [ {unit_info.get(\'hoNm\', ho_name)}호 전유부분 상세 정보 ]")',
        '            print("--------------------------------------------------")',
        '            print(f"  • 해당 층수  : {unit_info.get(\'flrNo\')}층")',
        '            if unit_info.get("area"):',
        '                pyung = round(unit_info["area"] * 0.3025, 1)',
        '                print(f"  • 전용면적  : {unit_info[\'area\']:.2f} ㎡ ({pyung}평)")',
        '                target_area = unit_info["area"]',
        '            if unit_info.get("supply_area"):',
        '                spyung = round(unit_info["supply_area"] * 0.3025, 1)',
        '                print(f"  • 공급면적  : {unit_info[\'supply_area\']:.2f} ㎡ ({spyung}평)")',
        '            try:',
        '                from serve_auto_upload import get_vworld_land_share',
        '                land_share = get_vworld_land_share(vworld_key, pnu, "", ho_name)',
        '                if land_share:',
        '                    l_area = float(land_share)',
        '                    l_pyung = round(l_area * 0.3025, 1)',
        '                    print(f"  • 대지지분  : {l_area:.2f} ㎡ ({l_pyung}평)")',
        '            except Exception as e:',
        '                print(f"대지지분 조회 중 오류: {e}")',
        '            viol_status = "⚠️ 위반건축물" if unit_info.get("viol_yn") == "Y" or unit_info.get("violBldYn") == "Y" else "정상 (위반 없음)"',
        '            print(f"  • 위반 여부  : {viol_status}")',
        '            apt_house_price = get_vworld_apartment_house_price(vworld_key, pnu, dong_name, ho_name)',
        '            if apt_house_price:',
        '                price_val = apt_house_price["price"]',
        '                formatted_p = format_assessed_price(price_val)',
        '                price_126 = int(price_val * 1.26)',
        '                formatted_126 = format_assessed_price(price_126)',
        '                print(f"  • 공동주택가격: {apt_house_price[\'year\']}년 기준 {formatted_p} (126%: {formatted_126})")',
        '            print("--------------------------------------------------")',
        '            try:',
        '                target_floor = int(re.sub(\'\\\\D\', \'\', str(unit_info.get("flrNo", "0"))))',
        '            except:',
        '                target_floor = 0',
        '        elif is_jibbap and ho_name:',
        '            print(f" [!] 전유부 대장에서 [{ho_name}호]의 상세 정보를 찾지 못했습니다.")',
        '        ',
        '        print("\\n[희망 거래 형태 선택]")',
        '        print("  1: 매매")',
        '        print("  2: 전세")',
        '        print("  3: 월세")',
        '        t_choice = input("[입력] 번호를 선택하세요 (1/2/3): ").strip()',
        '        while t_choice not in ("1", "2", "3"):',
        '            print(" [!] 올바른 번호(1, 2, 3)를 입력해 주세요.")',
        '            t_choice = input("[입력] 번호를 선택하세요 (1/2/3): ").strip()',
        '        trade_type_map = {"1": "매매", "2": "전세", "3": "월세"}',
        '        trade_type = trade_type_map[t_choice]',
        '        room_choice = ""',
        '        room_label = ""',
        '        if not is_jibbap and trade_type in ("전세", "월세"):',
        '            print("\\n [안내] 해당 건물은 호별 면적 구분이 없는 일반건축물(단독/다가구)입니다.")',
        '            print("        원활한 시세 비교(CMA)를 위해 분석할 임대차 매물의 방 개수 유형을 선택해 주세요.")',
        '            print("  1: 원룸 / 1.5룸형")',
        '            print("  2: 투룸형")',
        '            print("  3: 쓰리룸 이상형")',
        '            room_input = input("[입력] 번호를 선택하세요 (1/2/3): ").strip()',
        '            while room_input not in ("1", "2", "3"):',
        '                print(" [!] 올바른 번호(1, 2, 3)를 입력해 주세요.")',
        '                room_input = input("[입력] 번호를 선택하세요 (1/2/3): ").strip()',
        '            room_choice = room_input',
        '            if room_choice == "1":',
        '                room_label = "원룸/1.5룸형"',
        '                target_area = 20.0',
        '            elif room_choice == "2":',
        '                room_label = "투룸형"',
        '                target_area = 35.0',
        '            elif room_choice == "3":',
        '                room_label = "쓰리룸 이상형"',
        '                target_area = 55.0',
        '            floor_input = input("\\n[입력] 해당 임대차 매물의 층수를 입력해 주세요 (숫자만 입력, 예: 반지하는 -1, 1층은 1, 2층은 2 등): ").strip()',
        '            try:',
        '                target_floor = int(floor_input.replace("층", "").strip())',
        '            except:',
        '                target_floor = 1',
        '        client_phone = input("[입력] 의뢰인 전화번호 입력 (예: 010-1234-5678, 생략 시 엔터): ").strip()',
        '        target_price = 0',
        '        target_monthly = 0',
        '        if trade_type == "매매":',
        '            while True:',
        '                price_input = input("[입력] 매매 희망가 입력 (단위: 만원, 예: 85000): ").strip()',
        '                if price_input.isdigit():',
        '                    target_price = int(price_input)',
        '                    break',
        '                print(" [!] 숫자만 입력해 주세요.")',
        '        elif trade_type == "전세":',
        '            while True:',
        '                price_input = input("[입력] 보증금 입력 (단위: 만원, 예: 50000): ").strip()',
        '                if price_input.isdigit():',
        '                    target_price = int(price_input)',
        '                    break',
        '                print(" [!] 숫자만 입력해 주세요.")',
        '        elif trade_type == "월세":',
        '            while True:',
        '                dep_input = input("[입력] 보증금 입력 (단위: 만원, 예: 10000): ").strip()',
        '                if dep_input.isdigit():',
        '                    target_price = int(dep_input)',
        '                    break',
        '                print(" [!] 숫자만 입력해 주세요.")',
        '            while True:',
        '                mon_input = input("[입력] 월세 입력 (단위: 만원, 예: 150): ").strip()',
        '                if mon_input.isdigit():',
        '                    target_monthly = int(mon_input)',
        '                    break',
        '                print(" [!] 숫자만 입력해 주세요.")',
        '        desired_info = {"trade_type": trade_type, "price": target_price, "monthly_rent": target_monthly, "phone_number": client_phone, "room_count_choice": room_choice, "room_count_label": room_label}',
        '        print("\\n -> 최근 실거래(매매/임대차) 내역 및 자동 비교 조회 중...")',
        '        transactions = get_recent_transactions(addr_info["sigunguCd"], addr_info["bun"], addr_info["ji"], prop_type, addr_info.get("bjdongNm"), target_build_year, target_house_type)',
        '        trades = []',
        '        jeonses = []',
        '        wolses = []',
        '        prop_type_name = "일반 부동산"',
        '        selected_label = "최근 12개월"',
        '        is_expanded = False',
        '        if transactions:',
        '            trades = [t for t in transactions if t.get("trade_type") == "매매"]',
        '            jeonses = [t for t in transactions if t.get("trade_type") == "전세"]',
        '            wolses = [t for t in transactions if t.get("trade_type") == "월세"]',
        '            type_names = {"1": "아파트", "2": "연립/다세대/빌라", "3": "오피스텔", "4": "단독/다가구"}',
        '            prop_type_name = type_names.get(prop_type, "일반 부동산")',
        '        bld_data = {',
        '            "is_jibbap": is_jibbap,',
        '            "bld_nm": locals().get("bld_nm", ""),',
        '            "dong_nm": locals().get("dong_nm", ""),',
        '            "plat_area": locals().get("plat_area", 0.0),',
        '            "lndcgr": locals().get("lndcgr", ""),',
        '            "use_zone": locals().get("use_zone", ""),',
        '            "land_price_m2": locals().get("land_price_m2"),',
        '            "land_price_year": locals().get("land_price_year"),',
        '            "arch_area": locals().get("arch_area", 0.0),',
        '            "tot_area": locals().get("tot_area", 0.0),',
        '            "vl_rat_tot_area": locals().get("vl_rat_tot_area", 0.0),',
        '            "structure": locals().get("structure", ""),',
        '            "main_purp": locals().get("main_purp", ""),',
        '            "grnd_cnt": locals().get("grnd_cnt", 0),',
        '            "ugrnd_cnt": locals().get("ugrnd_cnt", 0),',
        '            "hhld": locals().get("hhld", 0),',
        '            "fmly": locals().get("fmly", 0),',
        '            "parking": locals().get("parking", 0),',
        '            "apr_day": locals().get("apr_day", ""),',
        '            "viol_str": locals().get("viol_str", "정상"),',
        '            "ride_elvt": locals().get("ride_elvt", 0),',
        '            "emgen_elvt": locals().get("emgen_elvt", 0),',
        '            "elvt_cnt": locals().get("elvt_cnt", 0),',
        '            "room_count_label": locals().get("room_label"),',
        '            "indiv_house_price": locals().get("indiv_house_price"),',
        '            "indiv_house_price_year": locals().get("indiv_house_price_year"),',
        '            "reg_info": locals().get("reg_info", {"moatown": False, "moatown_name": "", "redev": False, "redev_name": "", "permit": False, "permit_name": "", "regulated": False, "regulated_name": ""}),',
        '            "ho_details": locals().get("unit_info"),',
        '            "ho_name": locals().get("ho_name", ""),',
        '            "floor_map": locals().get("floor_map"),',
        '            "expos_list_count": locals().get("expos_list_count", 0),',
        '            "distinct_dongs": locals().get("distinct_dongs", []),',
        '            "floors": locals().get("floors", []),',
        '            "land_shares_raw": locals().get("items", [])',
        '        }',
        '        save_building_report(addr_info.get("road_address") or clean_address, bld_data)',
        '        from trade_viewer import save_briefing_report',
        '        display_addr = addr_info.get("road_address") or clean_address or "조회 대상 주소"',
        '        save_briefing_report(display_addr, trades, jeonses, wolses, prop_type_name, period_label=selected_label, is_expanded=is_expanded, target_build_year=target_build_year, target_area=target_area, target_floor=target_floor, desired_info=desired_info)',
        '        target_addr_str = addr_info.get("road_address") or clean_address',
        '        safe_addr_for_open = "".join([c for c in target_addr_str if c not in (" ", "-", "_")]).strip()',
        '        bld_pdf_path = os.path.abspath(f"종합분석보고서/건축물대장_{safe_addr_for_open.replace(\' \', \'_\')}.pdf")',
        '        brief_pdf_path = os.path.abspath(f"종합분석보고서/시세브리핑_{safe_addr_for_open.replace(\' \', \'_\')}.pdf")',
        '        opened_any = False',
        '        if sys.platform == "win32":',
        '            if os.path.exists(bld_pdf_path):',
        '                os.startfile(bld_pdf_path)',
        '                opened_any = True',
        '            if os.path.exists(brief_pdf_path):',
        '                os.startfile(brief_pdf_path)',
        '                opened_any = True',
        '        if opened_any:',
        '            print("\\n [안내] 생성된 PDF 보고서(건축물대장 및 시세브리핑)를 자동으로 실행하였습니다.")',
        '            print("        (종합분석보고서 폴더 내에 함께 저장되어 있습니다.)")',
        '        print("\\n==================================================")',
        '        upload_choice = input("[입력] 수집된 정보와 가격으로 부동산써브(Serve) 광고 자동 등록을 진행하시겠습니까? (y/n) [기본값: n]: ").strip().lower()',
        '        if upload_choice == "y":',
        '            sigungu_name = ""',
        '            if clean_address:',
        '                parts = clean_address.split(" ")',
        '                if len(parts) >= 2:',
        '                    sigungu_name = " ".join(parts[:2])',
        '            bunji_val = addr_info["bun"]',
        '            if addr_info.get("ji") and addr_info["ji"] != "0":',
        '                bunji_val += "-" + addr_info["ji"]',
        '            preset_data = {',
        '                "trade_type": trade_type,',
        '                "price": target_price,',
        '                "monthly_rent": target_monthly,',
        '                "phone_number": client_phone,',
        '                "sigunguCd": addr_info["sigunguCd"],',
        '                "bjdongCd": addr_info["bjdongCd"],',
        '                "sigungu_name": sigungu_name,',
        '                "bjdong_name": addr_info.get("bjdongNm", ""),',
        '                "bunji_val": bunji_val,',
        '                "ho_name": ho_name,',
        '                "dong_name": dong_nm',
        '            }',
        '            print(" -> 부동산써브 자동 매물 등록 연동을 시작합니다...")',
        '            from serve_auto_upload import run_serve_auto_upload',
        '            run_serve_auto_upload(preset_data)',
        '        print("═══════════════════════════════════════════════════════")',
        '    except Exception as e:',
        '        print(f"오류 발생: {e}")',
        '',
        'if __name__ == "__main__":',
        '    if sys.platform == "win32":',
        '        sys.stdin.reconfigure(encoding="utf-8", errors="replace")',
        '        sys.stdout.reconfigure(encoding="utf-8", errors="replace")',
        '        while True:',
        '            try:',
        '                run_building_viewer()',
        '            except KeyboardInterrupt:',
        '                break',
        '            except Exception as e:',
        '                print(f"오류 발생: {e}")'
    ]
    clean_lines.extend(run_building_viewer_code)

    return '\n'.join(clean_lines)

def verify_and_save(src_path, dest_path, clean_func):
    content = clean_func()
    try:
        compile(content, dest_path, 'exec')
        print(f"Success compiling {dest_path}!")
        open(dest_path, 'w', encoding='utf-8').write(content)
        return True
    except SyntaxError as e:
        open(dest_path, 'w', encoding='utf-8').write(content)
        err_text = str(e.text).encode('utf-8', errors='replace').decode('utf-8') if e.text else "None"
        print(f"SyntaxError in {dest_path} at line {e.lineno}: {err_text}")
        lines = content.splitlines()
        start = max(0, e.lineno - 5)
        end = min(len(lines), e.lineno + 5)
        for idx in range(start, end):
            line_str = lines[idx].encode('utf-8', errors='replace').decode('utf-8')
            print(f"{idx+1}: {line_str}")
        return False

if __name__ == '__main__':
    verify_and_save(
        r'D:\부동산업무\antigravity\consult_diary\scratch\중개수첩_오토봇.exe_extracted\PYZ.pyz_extracted\decompiled\trade_viewer.py',
        r'D:\부동산업무\antigravity\consult_diary\scratch\trade_viewer.py',
        clean_trade_viewer
    )
    verify_and_save(
        r'D:\부동산업무\antigravity\consult_diary\scratch\중개수첩_오토봇.exe_extracted\PYZ.pyz_extracted\decompiled\building_viewer.py',
        r'D:\부동산업무\antigravity\consult_diary\scratch\building_viewer.py',
        clean_building_viewer
    )
